### ISSUE TITLE
Allow Environment Variables within Artifactory destination URIs

### ISSUE THREAD

**Issue by mzimdars-gms-online-de** [tusharm/go-artifactory-plugin#18]
To be able to include build numbers into the target Uri of Artifactory, it would be great to be able to insert variables in ${xyz} style into the destintion uri

**Comment by pgeorgiev333** [comment]
Hi,
I just want to add that this request is absolutely mandatory. so +1

**Comment by zencodeuk** [comment]
Agreed, this is a must

**Comment by zencodeuk** [comment]
@pgeorgiev333 @mzimdars-gms-online-de you can pull from my fork until this PR is merged

https://github.com/zencodeuk/go-artifactory-plugin/releases/tag/1.0.0

**Comment by zencodeuk** [comment]
@mzimdars-gms-online-de please can you close this issue?

**Comment by pgeorgiev333** [comment]
I'm not using GO at the moment so it's impossible for me to test and close
it. Sorry

**Comment by mzimdars-gms-online-de** [comment]
Hi I can close it, but also I need some days to test it, so if I close it now, I cannot tell whether it's ok or not - would that be OK for you?

**Comment by zencodeuk** [comment]
of course  :+1:
